var Images = exports.Images = {
    bike_lane: './assets/bike_lane.png',
    background: './assets/background.png',
    biker: './assets/bike_test.png',
    cityhall: './assets/city_hall.png',
    hHouse01: './assets/house01.png',
    shrub01: './assets/shrub01.png',
    tree01: './assets/tree01.png',
    test_texture: './assets/road-texture.png',
    player_cart: './assets/player-sprite.png',
    enemy_cart_01: './assets/enemy1.png',
    lose_01: './assets/lose1.png',
    bully01: './assets/enemy-punching1.png',
    bully02: './assets/enemy-punching2.png',
    bully03: './assets/enemy-punching3.png',
    bully04: './assets/enemy-punching4.png',
    barricade01: './assets/enemy-roadbloack.png',
    // GUI
    mapOverlay: './assets/map.png',
    arrowLeft: './assets/arrow_left.png',
    arrowRight: './assets/arrow_right.png',
    stageClear: './assets/stage-clear.png',
    // Nature Theme
    bigRock: './assets/bigrock.png',
    rocks: './assets/rocks.png',
    tree02: './assets/tree02.png',
    tree03: './assets/tree03.png',
    tree04: './assets/tree04.png',
    tree05: './assets/tree05.png',
    tree06: './assets/tree06.png',
    shrub02: './assets/shrub02.png',
    shrub03: './assets/shrub03.png',
    water: './assets/water.png',
    // Ghost Theme
    ghostHouse03: './assets/ghosthouse03.png',
    ghostHouse05: './assets/ghosthouse05.png',
    ghostTree01: './assets/ghosttree01.png',
    ghostTree02: './assets/ghosttree02.png',
    ghostTree03: './assets/ghosttree03.png',
    // Town Theme
    house01: './assets/house01.png',
    house02: './assets/house02.png',
    house03: './assets/house03.png',
    house04: './assets/house04.png',
    house05: './assets/house05.png',
    house06: './assets/house06.png',
    house07: './assets/house07.png',
    // Lava Theme
    volcano01: './assets/volcano01.png',
    volcano02: './assets/volcano02.png',
    volcano03: './assets/volcano03.png',
    lava01: './assets/lava01.png',
    lava02: './assets/lava02.png',
    lavaTree01: './assets/lavatree01.png',
    lavaTree02: './assets/lavatree02.png',
    lavaTree03: './assets/lavatree03.png',
    // CUTSCENES
    cutscene01: './assets/cutscenes/intro-01.png',
    cutscene02: './assets/cutscenes/intro-02-layer-01.png',
    piece02: './assets/cutscenes/intro-02-layer-02.png',
    cutscene03: './assets/cutscenes/intro-03-layer-01.png',
    piece03_1: './assets/cutscenes/intro-03-layer-02.png',
    piece03_2: './assets/cutscenes/intro-03-layer-03.png',
    cutscene04: './assets/cutscenes/intro-04.png',
    cutscene05: './assets/cutscenes/intro-05-layer-01.png',
    piece05_1: './assets/cutscenes/intro-05-layer-02.png',
    piece05_2: './assets/cutscenes/intro-05-layer-03.png',
    piece05_3: './assets/cutscenes/intro-05-layer-04.png',
    piece05_4: './assets/cutscenes/intro-05-layer-05.png',
    cutscene06: './assets/cutscenes/intro-06-layer-01.png',
    piece06_1: './assets/cutscenes/intro-06-layer-02.png',
    piece06_2: './assets/cutscenes/intro-06-layer-03.png',
    piece06_3: './assets/cutscenes/intro-06-layer-04.png',
    cutscene07: './assets/cutscenes/intro-07-layer-01.png',
    piece07_1: './assets/cutscenes/intro-07-layer-02.png',
    piece07_2: './assets/cutscenes/intro-07-layer-03.png',
    piece07_3: './assets/cutscenes/intro-07-layer-04.png',
    cutscene08: './assets/cutscenes/intro-08-layer-01.png',
    piece08_1: './assets/cutscenes/intro-08-layer-02.png',
    piece08_2: './assets/cutscenes/intro-08-layer-03.png',
    piece08_3: './assets/cutscenes/intro-08-layer-04.png',
    titlescreen: './assets/cutscenes/titlescreen.png'
};

var sounds = exports.sounds = {
    blockade01: './assets/Blockade.ogg',
    blockade02: './assets/Blockade2.ogg',
    blockade03: './assets/Blockade3.ogg',
    glassbreak: './assets/Glassbreak.ogg',
    hit01: './assets/Hit.ogg',
    hit02: './assets/Hit2.ogg',
    hit03: './assets/Hit3.ogg',
    punch01: './assets/Punch.ogg',
    punch02: './assets/Punch2.ogg',
    punch03: './assets/Punch3.ogg',
    punch04: './assets/Punch4.ogg',
    punch05: './assets/Punch5.ogg',
    punch06: './assets/Punch6.ogg',
    schoolbell: './assets/schoolbell.ogg',
    ticktock: './assets/ticktock.ogg',
    woosh: './assets/Woosh.ogg'
}

var globals = exports.globals = {
    fps: 30
};